---
title: "Stand Up Fight Back"
subtitle: "How Police Killings Can Mobilize Local Communities"
thanks: Thanks.
author:
- Kevin Morris^[Brennan Center for Justice, Researcher (kevin.morris@nyu.edu)]
- Kelsey Shoub^[University of South Carolina, Assistant Professor (kshoub@mailbox.sc.edu)]
date: "`r format(Sys.time(), '%B %d, %Y')`"
bibliography: "shootings_to.bib"
output:
  bookdown::pdf_document2:
    toc: no
    fig_caption: yes
    latex_engine: xelatex
    keep_tex: true

link-citations: yes
fontsize: 12pt
header-includes:
    - \usepackage{rotating}
    - \usepackage{setspace}
abstract: |
  TKTKTKTK
---
\pagenumbering{gobble}
\pagebreak
\doublespacing
```{r setup, echo = F, message = F, warning = F}
knitr::opts_knit$set(root.dir = "..", dev = "cairo_pdf")
library(systemfit)
library(kevostools)
library(AER)
library(sandwich)
library(lmtest)
library(scales)
library(ggpubr)
library(tidyverse)
library(extrafont)
library(kableExtra)
library(data.table)
library(stargazer)
loadfonts()
```
\pagenumbering{arabic}

```{r map, echo = FALSE, message = F, warning = F, fig.width = 7.5, fig.height = 5, fig.cap = "\\label{fig:map}Police Killing within 2 Months of Election, 2016 and 2020", fig.pos = "h", fig.align = "center"}
print(readRDS("./temp/map.rds") + theme(text = element_text(size = 15)))
```

```{r map-16, echo = FALSE, message = F, warning = F, fig.width = 7.5, fig.height = 5, fig.cap = "\\label{fig:map}Police Killing within 2 Months of Election, 2016 and 2020", fig.pos = "h", fig.align = "center"}
print(readRDS("./temp/map_16.rds") + theme(text = element_text(size = 15)))
```

```{r diff-poly, echo = FALSE, message = F, warning = F, fig.width = 7.5, fig.height = 5, fig.cap = "\\label{fig:map}Police Killing within 2 Months of Election, 2016 and 2020", fig.pos = "h", fig.align = "center"}
print(readRDS("./temp/diff_polys_primary.rds") + theme(text = element_text(size = 15)))
```

```{r placebo-cuts, echo = FALSE, message = F, warning = F, fig.width = 7.5, fig.height = 5, fig.cap = "\\label{fig:map}Police Killing within 2 Months of Election, 2016 and 2020", fig.pos = "h", fig.align = "center"}
print(readRDS("./temp/placebos.rds") + theme(text = element_text(size = 15)))
```

```{r bws, echo = FALSE, message = F, warning = F, fig.width = 7.5, fig.height = 5.5, fig.cap = "\\label{fig:map}Police Killing within 2 Months of Election, 2016 and 2020", fig.pos = "h", fig.align = "center"}
print(readRDS("temp/alt_bws_rdd.rds") + theme(text = element_text(size = 15)))
```


```{r alt-proc, echo = FALSE, message = F, warning = F, fig.width = 7.5, fig.height = 5.5, fig.cap = "\\label{fig:map}Police Killing within 2 Months of Election, 2016 and 2020", fig.pos = "h", fig.align = "center"}
print(readRDS("temp/alt_proc_rdd.rds") + theme(text = element_text(size = 15)))
```

```{r placebo-prior, echo = FALSE, message = F, warning = F, fig.width = 7.5, fig.height = 5, fig.cap = "\\label{fig:map}Police Killing within 2 Months of Election, 2016 and 2020", fig.pos = "h", fig.align = "center"}
print(readRDS("./temp/placebo-prior.rds") + theme(text = element_text(size = 15)))
```

```{r did-length, echo = FALSE, message = F, warning = F, fig.width = 7.5, fig.height = 5, fig.cap = "\\label{fig:map}Police Killing within 2 Months of Election, 2016 and 2020", fig.pos = "h", fig.align = "center"}
print(readRDS("./temp/did_length.rds") + theme(text = element_text(size = 15)))
```

```{r did-week, echo = FALSE, message = F, warning = F, fig.width = 7.5, fig.height = 5, fig.cap = "\\label{fig:map}Police Killing within 2 Months of Election, 2016 and 2020", fig.pos = "h", fig.align = "center"}
print(readRDS("./temp/did_week.rds") + theme(text = element_text(size = 15)))
```


```{r rd-plot, echo = FALSE, message = F, warning = F, fig.width = 7.5, fig.height = 5, fig.cap = "\\label{fig:map}Police Killing within 2 Months of Election, 2016 and 2020", fig.pos = "h", fig.align = "center"}
print(readRDS("./temp/rd_plot.rds") + theme(text = element_text(size = 15)))
```

```{r dists, echo = FALSE, message = F, warning = F, fig.width = 7.5, fig.height = 5, fig.cap = "\\label{fig:map}Police Killing within 2 Months of Election, 2016 and 2020", fig.pos = "h", fig.align = "center"}
print(readRDS("temp/different_dists_primary.rds") + theme(text = element_text(size = 15)))
```


```{r nhood, echo = FALSE, message = F, warning = F, fig.width = 7.5, fig.height = 5, fig.cap = "\\label{fig:map}Police Killing within 2 Months of Election, 2016 and 2020", fig.pos = "h", fig.align = "center"}
print(readRDS("temp/plurality_nhood.rds") + theme(text = element_text(size = 15)))
```


```{r victim, echo = FALSE, message = F, warning = F, fig.width = 7.5, fig.height = 5, fig.cap = "\\label{fig:map}Police Killing within 2 Months of Election, 2016 and 2020", fig.pos = "h", fig.align = "center"}
print(readRDS("temp/victim_race.rds") + theme(text = element_text(size = 15)))
```

```{r minn-scatter, echo = FALSE, message = F, warning = F, fig.width = 7.5, fig.height = 5, fig.cap = "\\label{fig:map}Police Killing within 2 Months of Election, 2016 and 2020", fig.pos = "h", fig.align = "center"}
print(readRDS("temp/minn_scatter.rds") + theme(text = element_text(size = 15)))
```

```{r paneled-race-effects, echo = FALSE, message = F, warning = F, fig.width = 7.5, fig.height = 5, fig.cap = "\\label{fig:map}Police Killing within 2 Months of Election, 2016 and 2020", fig.pos = "h", fig.align = "center"}
print(readRDS("temp/all_plots.rds") + theme(text = element_text(size = 15)))
```

```{r first-difference, echo = FALSE, message = F, warning = F, fig.width = 7.5, fig.height = 5, fig.cap = "\\label{fig:map}Police Killing within 2 Months of Election, 2016 and 2020", fig.pos = "h", fig.align = "center"}
print(readRDS("temp/first_diff_plot.rds") + theme(text = element_text(size = 15)))
```

\begin{singlespace}

 
```{r balance-tab-full, echo = F}

t <- readRDS("temp/demo_table_half_mile.rds") %>% 
  select(-Year)
colnames(t)[1] <- ""
j <- knitr::kable(t, booktabs = T, caption = "(\\#tab:full-bal) Demographics of Block Groups with Police Killings", linesep = "") %>%
  kable_styling(latex_options = c("HOLD_position")) %>% 
  pack_rows("2016", 1, 10) %>%
  pack_rows("2020", 11, 20) %>% 
  column_spec(2:5, width = "1in")
 
j

``` 
 
\end{singlespace}